const sampleLoads = [
  {
    id: 1,
    from: "Chennai",
    to: "Sriperumbudur",
    vehicleType: "Open Body",
    distance: "45 km",
    weight: "12,000 kg",
    price: 8500,
    pickupTime: "Today 2:00 PM",
  },
  {
    id: 2,
    from: "Chennai",
    to: "Chengalpattu",
    vehicleType: "Closed Body",
    distance: "60 km",
    weight: "8,000 kg",
    price: 7200,
    pickupTime: "Today 5:30 PM",
  },
  {
    id: 3,
    from: "Chennai",
    to: "Kanchipuram",
    vehicleType: "MCV",
    distance: "75 km",
    weight: "10,500 kg",
    price: 9800,
    pickupTime: "Tomorrow 9:00 AM",
  },
  {
    id: 4,
    from: "Tambaram",
    to: "Vellore",
    vehicleType: "LCV",
    distance: "140 km",
    weight: "3,500 kg",
    price: 6500,
    pickupTime: "Tomorrow 6:00 AM",
  },
  {
    id: 5,
    from: "Chennai",
    to: "Tiruvallur",
    vehicleType: "SCV",
    distance: "42 km",
    weight: "2,000 kg",
    price: 4200,
    pickupTime: "Today 8:00 PM",
  },
  {
    id: 6,
    from: "Guindy",
    to: "Hosur",
    vehicleType: "Open Body",
    distance: "310 km",
    weight: "15,000 kg",
    price: 18500,
    pickupTime: "Tomorrow 7:00 AM",
  },
];

export default sampleLoads;
